name: Lint

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Check precommit hooks
      uses: pre-commit/action@v3.0.0
