name: PyPIRelease

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Pip Dependencies
      shell: bash
      run: pip install --upgrade build

    - name: Build the Wheel
      shell: bash
      run: rm -rf dist/ build/ && python3 -m build

    - name: Deploy on Test PyPi
      if: contains(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPIPW }}
