name: PyPIRelease

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Pip Dependencies
      shell: bash
      run: pip install -e .[dev]

    - name: Build the Wheel
      shell: bash
      run: rm -rf dist/ build/ && python3 -m build

    - name: Deploy on Test PyPi
      uses: pypa/gh-action-pypi-publish@37f50c210e3d2f9450da2cd423303d6a14a6e29f  # v1.5.1
      with:
        user: __token__
        password: ${{ secrets.PYPIPW }}
