name: Test

on: [ push ]

env:
  PYTHONPATH: '.'

jobs:
  download_and_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v2
      - name: Set up Python 3.8
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5  # v4.2.0
        with:
          python-version: 3.8
#      - uses: suisei-cn/actions-download-file@v1.3.0
#        name: Download EnergyPlus
#        with:
#          url: "https://github.com/NREL/EnergyPlus/releases/download/v22.2.0/EnergyPlus-22.2.0-c249759bad-Linux-Ubuntu22.04-x86_64.tar.gz"
#          target: energyplus/
      - name: Download EnergyPlus
        run: wget https://github.com/NREL/EnergyPlus/releases/download/v22.2.0/EnergyPlus-22.2.0-c249759bad-Linux-Ubuntu22.04-x86_64.tar.gz -O energyplus.tar.gz
      - name: Extract EnergyPlus
        run: tar -xvf energyplus.tar.gz
      - name: Run Example Script
        run: python ./eplus_api_helpers/demos/01_simple_library_call.py ./EnergyPlus-22.2.0-c249759bad-Linux-Ubuntu22.04-x86_64
